
var luierpunten = [
    {
        "name": "Kinderopvang Prins Vleermuis",
        "coordinate": [52.035159, 5.677061],
        "address": "Nieuwe Kazernelaan 2",
        "postalcode": "6711 JC",
        "city": "Ede",
        "remarks": "",
    },
    {
        "name": "Kinderdagverblijf Platteelhof",
        "coordinate": [52.039944, 5.672754],
        "address": "Platteelhof 3",
        "postalcode": "6711 JK",
        "city": "Ede",
        "remarks": "",
    },
    {
        "name": "Kinderdagverblijf Eigen Wijs",
        "coordinate": [52.038140, 5.677981],
        "address": "Van Heutszlaan 60a",
        "postalcode": "6711 KR",
        "city": "Ede",
        "remarks": "",
    },
    {
        "name": "Kindcentrum Het Sterrenbos",
        "coordinate": [52.045225, 5.666416],
        "address": "Veenderweg 4",
        "postalcode": "6712 AB",
        "city": "Ede",
        "remarks": "achter de zij-ingang aan de Telefoonweg, alleen op werkdagen van 7.00 tot 18.30 uur",
    },
    {
        "name": "Peuteropvang 't Onderdeurtje",
        "coordinate": [52.038948, 5.659166],
        "address": "Wulplaan 9",
        "postalcode": "6713 BT",
        "city": "Ede",
        "remarks": "alleen brengen tijdens schoolperioden en schooldagen van 08.30 tot 14.30 uur",
    },
    {
        "name": "Happy Kids",
        "coordinate": [52.032199, 5.658892],
        "address": "Prins Hendriklaan 7",
        "postalcode": "6713 NE",
        "city": "Ede",
        "remarks": "",
    },
    {
        "name": "Kinderdagverblijf Pollenstein",
        "coordinate": [52.043773, 5.647957],
        "address": "Pollenstein 1",
        "postalcode": "6714 DK",
        "city": "Ede",
        "remarks": "",
    },
    {
        "name": "Peuteropvang De Blokkendoos",
        "coordinate": [52.046209, 5.64389],
        "address": "Lindenhorst 1",
        "postalcode": "6714 EJ",
        "city": "Ede",
        "remarks": "",
    },
    {
        "name": "De Veldmuis",
        "coordinate": [52.041801, 5.632918],
        "address": "Ridderhof 5",
        "postalcode": "6715 EL",
        "city": "Ede",
        "remarks": "",
    },
    {
        "name": "Peuteropvang De Rode Wonderkist",
        "coordinate": [52.024073, 5.638795],
        "address": "Professor Oudpark 4",
        "postalcode": "6716 EJ",
        "city": "Ede",
        "remarks": "",
    },
    {
        "name": "Kinderopvang De Rots",
        "coordinate": [52.026039, 5.653226],
        "address": "Verlengde Parkweg 49",
        "postalcode": "6717 GL",
        "city": "Ede",
        "remarks": "bij basisschool De Rots",
    },
    {
        "name": "Kinderdagverblijf Het Vlinderbos",
        "coordinate": [52.022992, 5.671468],
        "address": "Bennekomseweg 32",
        "postalcode": "6717 LM",
        "city": "Ede",
        "remarks": "",
    },
    {
        "name": "Jottum! Kinderdagverblijf",
        "coordinate": [52.019339, 5.654138],
        "address": "Mondriaanstraat 21",
        "postalcode": "6717 SC",
        "city": "Ede",
        "remarks": "",
    },
    {
        "name": "Peuteropvang Spetter Spat",
        "coordinate": [52.052894, 5.640662],
        "address": "Distelberg 1",
        "postalcode": "6718 EB",
        "city": "Ede",
        "remarks": "",
    },
    {
        "name": "Afvalbrengstation",
        "coordinate": [52.043148, 5.616061],
        "address": "Neonstraat 4",
        "postalcode": "6718 WV",
        "city": "Ede",
        "remarks": "",
    },
    {
        "name": "Bzzzonder",
        "coordinate": [52.051997, 5.675253],
        "address": "Otterloseweg 18a",
        "postalcode": "6718 ZM",
        "city": "Ede",
        "remarks": "alleen brengen op werkdagen van 07.30 uur tot 18.30 uur",
    },
    {
        "name": "Siza Schoolstraat",
        "coordinate": [52.000684, 5.677195],
        "address": "Schoolstraat 18-6",
        "postalcode": "6721 CS",
        "city": "Bennekom",
        "remarks": "",
    },
    {
        "name": "SC Peuterspeelzaal de Bijenkorf",
        "coordinate": [52.012028, 5.626331],
        "address": "Rijnsteeg 5",
        "postalcode": "6721 NP",
        "city": "Bennekom",
        "remarks": "",
    },
    {
        "name": "Kinderdagverblijf Bennekom",
        "coordinate": [52.012100, 5.674428],
        "address": "Oost Breukelderweg 1a",
        "postalcode": "6721 PG",
        "city": "Bennekom",
        "remarks": "",
    },
    {
        "name": "Kinderopvang Harskamp",
        "coordinate": [52.126128, 5.750792],
        "address": "Molenweg 8a",
        "postalcode": "6732 BP",
        "city": "Harskamp",
        "remarks": "",
    },
    {
        "name": "Opella Metje",
        "coordinate": [52.133315, 5.752692],
        "address": "Smachtenburgerhof 1",
        "postalcode": "6732 CD",
        "city": "Harskamp",
        "remarks": "",
    },
    {
        "name": "Kulturhus De Hooge Valk",
        "coordinate": [52.121099, 5.670632],
        "address": "Hoge Valkseweg 52a",
        "postalcode": "6741 AA",
        "city": "Lunteren",
        "remarks": "",
    },
    {
        "name": "Opella de Honskamp",
        "coordinate": [52.081912, 5.623186],
        "address": "Dorpsstraat 25",
        "postalcode": "6741 AA",
        "city": "Lunteren",
        "remarks": "op Beeklaantje naast de grote boom bij Opella",
    },
    {
        "name": "Partou Kinderopvang",
        "coordinate": [52.080291, 5.619953],
        "address": "Kerkhoflaan 31",
        "postalcode": "6741 BN",
        "city": "Lunteren",
        "remarks": "",
    },
    {
        "name": "Voorschoolseopvang De Valkjes",
        "coordinate": [52.118918, 5.684095],
        "address": "Hoge Valkseweg 37",
        "postalcode": "6741 GK",
        "city": "Lunteren",
        "remarks": "",
    },
    {
        "name": "De Wiebelwagen",
        "coordinate": [52.061749, 5.580232],
        "address": "Hootsenstraat 24",
        "postalcode": "6744 AJ",
        "city": "Ederveen",
        "remarks": "",
    }
];